server:
  port: 9090

mybatis:
  type-aliases-package: com.cloud.frame.demo.reactive.entity
  configuration:
    # 全局启用或禁用延迟加载。当禁用时，所有关联对象都会即时加载。
    lazyLoadingEnabled: true
    # 当启用时，有延迟加载属性的对象在被调用时将会完全加载任意属性。否则，每种属性将会按需要加载。
    aggressiveLazyLoading: true
    # 是否允许单条sql 返回多个数据集  (取决于驱动的兼容性) default:true
    multipleResultSetsEnabled: true
    # 是否可以使用列的别名 (取决于驱动的兼容性) default:true
    useColumnLabel: true
    # 指定 MyBatis 如何自动映射 数据基表的列 NONE：不隐射　PARTIAL:部分  FULL:全部
    autoMappingBehavior: partial
    # 这是默认的执行类型  （SIMPLE: 简单； REUSE: 执行器可能重复使用prepared statements语句；BATCH: 执行器可以重复执行语句和批量更新）
    defaultExecutorType: simple
    # 在执行查询后，可以将数据库的NN_NN格式字段，在java结果集对象中自动转换成驼峰命名参数
    mapUnderscoreToCamelCase: true
    # 设置本地缓存范围 session:就会有数据的共享  statement:语句范围 (这样就不会有数据的共享 ) defalut:session
    localCacheScope: session
    # 设置但JDBC类型为空时,某些驱动程序 要指定值,default:OTHER，插入空值时不需要指定类型
    jdbcTypeForNull: null
    # defaultStatementTimeout: 30

logging:
  level:
    com.cloud.frame.demo.reactive: DEBUG

spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://192.168.90.206:3306/bootdemo?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: 123456
      schema: classpath:db/v0.0.1.sql
  # REDIS (RedisProperties)
  # 其中spring.redis.database的配置通常使用0即可，
  # Redis在配置的时候可以设置数据库数量，默认为16，可以理解为数据库的schema
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 192.168.90.206
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接超时时间（毫秒）
    timeout: 0

