server:
  port: 9411
  undertow:
    accesslog:
      enabled: true


#spring:
#  cloud:
#    consul:
#      host: localhost
#      port: 8500
#      discovery:
#        instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${service.port}}
#        service-name: springcloud-zipkin-service

#logging:
#  level: org.springframework.web.servlet.DispatcherServlet=DEBUG
#