server:
  port: 8888

eureka:
  instance:
    hostname: registry
    prefer-ip-address: true
#    metadata-map:
#      user.name: ${security.user.name}
#      user.password: ${security.user.password}
  client:
    service-url:
      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:password}@registry:8761/eureka/

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zixcon/cloud-proj
          search-paths: config-repo
#  rabbitmq:
#    host: rabbitmq
#    stream:
#      kafka:
#        binder:
#          brokers: localhost:9092
#          zk-nodes: 10.79.96.52:2182

#security:
#  user:
#    name: user
#    password: ${CONFIG_SERVER_PASSWORD:password}

#service:
#  port: 8888
#
#management:
#  context-path: /admin
#
#logging:
#  level:
#    com.netflix.discovery: 'OFF'
#    org.springframework.cloud: 'DEBUG'
#
#eureka:
#  instance:
#    leaseRenewalIntervalInSeconds: 10
#    statusPageUrlPath: /admin/info
#    healthCheckUrlPath: /admin/health
#
#spring:
#  cloud:
#    config:
#      service:
#        git:
#          uri: https://github.com/spring-cloud-samples/config-repo
#          basedir: target/config
#
#---
#spring:
#  profiles: cloud
#eureka:
#  password: password
#  instance:
#    hostname: ${vcap.application.uris[0]}
#    nonSecurePort: 80
#  client:
#    serviceUrl:
#      defaultZone: ${vcap.services.${PREFIX:}eureka.credentials.uri:http://user:${eureka.password:}@${PREFIX:}eureka.${application.domain:cfapps.io}}/eureka/

