server:
  port: 8761

#eureka:
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#  service:
#    waitTimeInMsWhenSyncEmpty: 0

eureka:
  instance:
    hostname: registry
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#      defaultZone: http://${security.user.name}:${security.user.password}@${eureka.instance.hostname}:${service.port}/eureka/

#security:
#  user:
#    name: user
#    password: ${REGISTRY_SERVER_PASSWORD:password}