
spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/bootdemo?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: 123456
      schema: classpath:db/v0.0.1.sql

mybatis:
  type-aliases-package: com.cloud.frame.demo.dao.**.entity
  mapper-locations: classpath*:/generator/mapper/**/*Mapper.xml
  configLocation: classpath*:/generator/mybatis-config.xml

jwt:
  header: Authorization
  secret: yoursecret
  expiration: 604800
  tokenHead: Bearer

logging:
  # 如果只配置 logging.file ，会在项目的当前路径下生成一个 xxx.log 日志文件。
  # 如果只配置 logging.path ，在 /var/log 文件夹生成一个日志文件为 spring.log
  # 注：二者不能同时使用，如若同时使用，则只有 logging.file 生效
  file: logs/ucenter.log
#  path: /Users/wd/Documents/dev/git/cloud-proj/cloud-proj/frame/cloud-frame/logs/
  config: classpath:spring/logback-spring.xml
  level:
    com.cloud.frame.demo.auth: DEBUG
  pattern:
    console: "[%d{HH:mm:ss.SSS}] [%thread] [%X{traceId}] [%-5level] %logger{36} - %msg%n"

