spring:
  application:
    name: cloud-frame-demo-provider

server:
  port: 8081

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    hostname: registry
    prefer-ip-address: true
#    metadata-map:
#      user.name: ${security.user.name}
#      user.password: ${security.user.password}
  client:
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:password}@registry:8761/eureka/

# Hystrix默认的超时时间是1秒，如果超过这个时间尚未响应，将会进入fallback代码; 这里修改超时时间
# 让Hystrix的超时时间改为60秒
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000
      # 禁用Hystrix的超时时间
#        timeout:
#          enabled: false
