version: "3"
services:
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
#    volumes:
#      - '/data/log:/data/log'
  reactive-web:
    image: cloud-frame-demo/cloud-frame-demo-reactive-web:0.0.1
    ports:
      - '9090:9090'
#    volumes:
#      - '/data/logs:/data/logs'
#    depends_on:
#      links:
#        - redis
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.90.194
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

