server:
  port: 8765

#info:
#  component: Zuul Server

#endpoints:
#  restart:
#    enabled: true
#  shutdown:
#    enabled: true
#  health:
#    sensitive: false

eureka:
  instance:
    hostname: registry
    prefer-ip-address: true
#    metadata-map:
#      user.name: ${security.user.name}
#      user.password: ${security.user.password}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:password}@registry:8761/eureka/



zuul:
  sensitiveHeaders: Authorization,traceId
  routes:
    demo-provider:
      path: /demo/provider/**
      serviceId: cloud-frame-demo-provider
      strip-prefix: false
    demo-consumer:
      # prefix: /consumer1
      path: /consumer1/**
      serviceId: cloud-frame-demo-consumer
      strip-prefix: true
    ucenter:
      # prefix: /ucenter
      path: /ucenter/**
      serviceId: ucenter
      strip-prefix: true

# demo-provider:
#  ribbon:
#    listOfServers: 192.168.90.33:8081 # 192.168.90.33:8081,192.168.90.33:8082
#
# demo-consumer:
#  ribbon:
#    listOfServers: 192.168.90.33:8091 # 192.168.90.33:8091,192.168.90.33:8092


# com.netflix.zuul.exception.ZuulException: Forwarding error
ribbon:
# 为了同时指定path 和 url，但是不破坏Zuul的Hystrix和Ribbon特性：
  eureka:
    enabled: true # ribbon禁掉Eureka
# #请求处理的超时时间
  ReadTimeout: 10000
# #请求连接的超时时间
  ConnectTimeout: 5000


# 不配置则FeignClient的callback不起作用
feign:
  hystrix:
    enabled: true

hystrix.command.default.execution.timeout.enabled: false

