server:
  port: 8765

#info:
#  component: Zuul Server

#endpoints:
#  restart:
#    enabled: true
#  shutdown:
#    enabled: true
#  health:
#    sensitive: false

eureka:
  instance:
    hostname: registry
    prefer-ip-address: true
#    metadata-map:
#      user.name: ${security.user.name}
#      user.password: ${security.user.password}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:password}@registry:8761/eureka/

zuul:
  addProxyHeaders: false
  ignoredServices: '*'
#  prefix: /api
  # strip-prefix 放这里 全局 ，放在 routes下 局部
  # strip-prefix: false
  routes:
    demo-provider: # 路由名称，随意，唯一即可
      # 表示只要HTTP请求是/demo/provider开始的，就会forward到服务id为cloud-frame-demo-provider的服务上面
      path: /demo/provider/** # 路由路径
      serviceId: cloud-frame-demo-provider # 服务id 或者直接制定地址 http://192.168.90.33:8081
      strip-prefix: false # 去掉前缀
      # strip-prefix: true
      # http://192.168.90.33:8765/api/cloud-frame-demo-provider/demo/provider/print/sdf
      # 等价于 http://192.168.90.33:8081/demo/provider/print/sdf
      # strip-prefix: false
      # http://192.168.90.33:8765/api/demo/provider/print/sdf
      # 等价于 http://192.168.90.33:8081/demo/provider/print/sdf
    demo-consumer:
      prefix: /api
      path: /demo/consumer/**
      serviceId: cloud-frame-demo-consumer
      strip-prefix: false
    ucenter:
      # prefix: /ucenter
      path: /ucenter/** # 路由路径
      serviceId: ucenter
      strip-prefix: true # 去掉前缀

demo-provider:
  ribbon:
    listOfServers: 192.168.90.33:8081 # 192.168.90.33:8081,192.168.90.33:8082

demo-consumer:
  ribbon:
    listOfServers: 192.168.90.33:8091 # 192.168.90.33:8091,192.168.90.33:8092

# 为了同时指定path 和 url，但是不破坏Zuul的Hystrix和Ribbon特性：
ribbon:
  eureka:
    enabled: false # ribbon禁掉Eureka

# com.netflix.zuul.exception.ZuulException: Forwarding error
ribbon:
##请求处理的超时时间
  ReadTimeout: 10000
##请求连接的超时时间
  ConnectTimeout: 5000

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG